### PR TITLE
fix: don't use solar_energy if 0 when it shouldn't be

### PR DESCRIPTION
**Pull request by marcusds**
For more details see #245 

This is untested and probably not the right way to do this, I'm not super familiar with Python or this project, but just thought I would give it a whack anyhow.

### CODE REVIEW

**Comment by marcusds** [comment]
Small sample size, but for the couple days I've been running this it's worked as intended. 

I wonder if it's worth releasing a beta build for?

@HAEdwin

**Comment by HAEdwin** [comment]
@marcusds The second check on the number of inverters is unnecessary because this value is not being changed (not even when inverters are offline), unless an inverter is added or removed from the configuration.

**Comment by marcusds** [comment]
@HAEdwin Yeah I was wondering if the bug could be entirely worked around with how you are processing the data? I also wonder if that you can't do that if the whole query should be scrapped because if some data is bad, maybe all data is bad?

**Comment by HAEdwin** [comment]
Well it's just a firmware bug because the checksum (length of datastream) and datamapping is correct it is easy to apply a filter. This should be the final result then, agree?

**Comment by marcusds** [comment]
Sounds good

**Pull request merged**
